export interface MenuItem {
  name: string;
  price?: string;
  tag?: string;
}

export interface MenuCategory {
  id: string;
  title: string;
  kicker: string;
  items: MenuItem[];
}

export const MENU: MenuCategory[] = [
  {
    id: "poultry-fresh",
    title: "Poultry · Fresh",
    kicker: "Category 01",
    items: [
      { name: "Whole Chicken Chilled" },
      { name: "Chicken Breast Chilled" },
      { name: "Chicken Thighs Chilled" },
      { name: "Chicken Wings Chilled" },
      { name: "Chicken Drumsticks Chilled" },
      { name: "Chicken Breast & Wing Chilled" },
      { name: "Chicken Center Breast" },
      { name: "Chicken Whole Legs Chilled" },
      { name: "Minced Chicken" },
      { name: "Chicken Breast - Boneless" },
      { name: "Chicken Thighs - Boneless" },
      { name: "Boneless Chicken Breast (Kebabs)" },
      { name: "Chicken Breast Tenders" },
      { name: "Duck (Local)" },
      { name: "Chicken Liver" },
      { name: "Chicken Gizzard" },
      { name: "Chicken Feet" },
      { name: "Chicken Neck" },
      { name: "Chicken Neck & Back" },
      { name: "Chicken Breast Bone" },
    ],
  },
  {
    id: "poultry-seasoned",
    title: "Poultry · Seasoned",
    kicker: "Category 02",
    items: [
      { name: "Whole Chicken - Seasoned", price: "22" },
      { name: "Chicken Drumsticks - Seasoned", price: "22" },
      { name: "Chicken Breast Boneless - Seasoned", price: "30" },
      { name: "Chicken Breast - Seasoned", price: "20" },
      { name: "Chicken Thighs - Seasoned", price: "19" },
      { name: "Chicken Wings - Seasoned", price: "22" },
      { name: "Chicken Breast & Wing - Seasoned", price: "20" },
      { name: "Chicken Gizzard - Seasoned", price: "11" },
      { name: "Chicken Whole Legs - Seasoned", price: "20" },
      { name: "Chicken Quarters - Seasoned", price: "20" },
      { name: "Chicken Breast Tenders - Seasoned", price: "28" },
      { name: "Chicken Mixed Pack - Seasoned", price: "20" },
      { name: "Duck - Seasoned", price: "30" },
      { name: "Whole Chicken - Jerk Seasoned", price: "25" },
      { name: "Chicken Thighs - Mediterranean Herb Seasoned", price: "19" },
      { name: "Chicken Drumsticks - Mediterranean Herb", price: "22" },
      { name: "Whole Chicken - Mediterranean Herb Seasoned", price: "25" },
      { name: "Chicken Breast - Mediterranean Herb Seasoned", price: "20" },
      {
        name: "Chicken Whole Legs - Mediterranean Herb Seasoned",
        price: "19",
      },
      { name: "Chicken Wings - Mediterranean Herb Seasoned", price: "22" },
      { name: "Chicken Mixed Pack - Mediterranean Herb Seasoned", price: "22" },
      {
        name: "Chicken Mixed Pack - Spicy Khan's Herb Seasoned",
        price: "22",
        tag: "Mild",
      },
      {
        name: "Whole Chicken - Spicy Khan's Herb Seasoned",
        price: "25",
        tag: "Mild",
      },
      {
        name: "Chicken Thighs Boneless - Spicy Khan's Herb Seasoned",
        price: "30",
        tag: "Mild",
      },
      {
        name: "Chicken Thighs - Spicy Khan's Herb Seasoned",
        price: "19",
        tag: "Mild",
      },
      {
        name: "Chicken Drumsticks - Spicy Khan's Herb Seasoned",
        price: "22",
        tag: "Mild",
      },
      {
        name: "Chicken Breasts - Spicy Khan's Herb Seasoned",
        price: "22",
        tag: "Mild",
      },
      {
        name: "Chicken Whole Legs - Spicy Khan's Herb Seasoned",
        price: "22",
        tag: "Mild",
      },
      {
        name: "Chicken Wings - Spicy Khan's Herb Seasoned",
        price: "22",
        tag: "Mild",
      },
      { name: "Chicken Cut Up - Geera Seasoned", price: "22" },
      { name: "Chicken Tenders - Breaded", price: "26" },
    ],
  },
  {
    id: "specialty-meats",
    title: "Specialty Meats",
    kicker: "Category 03",
    items: [
      { name: "Beef Clod - Sliced", price: "27" },
      { name: "Beef Stew", price: "27" },
      { name: "Beef Clod - Seasoned", price: "32" },
      { name: "Minced Beef", price: "26" },
      { name: "Beef Clod Sliced - Seasoning", price: "32" },
      { name: "Beef Liver", price: "14" },
      { name: "Beef Stir Fry", price: "30" },
      { name: "Cow Heel", price: "13" },
      { name: "Beef Trimmings", price: "17.50" },
      { name: "Beef Clod Roast", price: "27" },
      { name: "Beef Soup Bone", price: "14" },
      { name: "Beef Striploin NZ", price: "90" },
      { name: "Beef Shortloin NZ", price: "86" },
      { name: "Beef T-Bone Steak NZ", price: "86" },
      { name: "Beef Ribeye NZ", price: "104" },
      { name: "Goat Cut Up", price: "35" },
      { name: "Goat Leg", price: "38" },
      { name: "Goat Cut Up Seasoned", price: "40" },
      { name: "Stir Fry Lamb Chops", price: "34" },
      { name: "Minced Lamb - Seasoned", price: "45" },
      { name: "Lamb Loin Chops", price: "154" },
      { name: "Lamb Shoulder Whole", price: "32" },
      { name: "Lamb Chops - Seasoned", price: "39" },
      { name: "Lamb Shoulder Center Cut", price: "34" },
      { name: "Lamb Shoulder Sliced", price: "32" },
      { name: "Lamb Stew", price: "15" },
      { name: "Lamb Stew Seasoned", price: "20" },
      { name: "Lamb Leg Whole", price: "45" },
      { name: "Lamb Rack", price: "140" },
      { name: "Lamb Rack Seasoned", price: "150" },
      { name: "Minced Lamb", price: "40" },
      { name: "Lamb Rib Chops", price: "34" },
      { name: "Lamb Leg Boneless", price: "70" },
      { name: "Lamb Loin NZ", price: "62" },
      { name: "Lamb Loin NZ Seasoned", price: "65" },
      { name: "Oxtail", price: "37" },
      { name: "Turkey Wings", price: "15" },
      { name: "Turkey Drumsticks", price: "20" },
      { name: "Turkey Stew Seasoned", price: "20" },
    ],
  },
  {
    id: "seafood",
    title: "Seafood",
    kicker: "Category 04",
    items: [
      { name: "Mahi Mahi Fillet Skin Off", price: "60" },
      { name: "Mahi Mahi Seasoned", price: "65" },
      { name: "White Marlin Steaks", price: "35" },
      { name: "White Marlin Seasoned", price: "33" },
      { name: "King Fish", price: "30" },
      { name: "King Fish Seasoned", price: "35" },
      { name: "Carite Fish", price: "29" },
      { name: "Carite Fish Seasoned", price: "34" },
      { name: "Salmon Fish Fillet", price: "25" },
      { name: "Salmon Fillet Skin On", price: "24" },
      { name: "Pink Salmon Fillet - Skin On", price: "80" },
      { name: "Lambie", price: "45" },
      { name: "Shark Fillet", price: "24" },
      { name: "Smoked Herring Fillet", price: "37" },
      { name: "Choice Smoked Herring", price: "17" },
      { name: "Tuna Steak", price: "45" },
      { name: "Fresh Shrimp", price: "45" },
      { name: "Oyster Bay - Supreme Crab Meat", price: "85" },
      { name: "Chilean Salmon Portions", price: "47" },
      { name: "Ocean Delight Extra Jumbo Shrimp Raw", price: "105" },
      {
        name: "Ocean Delight Small Shrimp Raw, Peeled & Deveined",
        price: "55",
      },
      { name: "Ocean Delight Large Shrimp Raw Ez Peel", price: "68" },
      { name: "Ocean Delight Jumbo Easy Peel Shrimp", price: "79" },
      { name: "Ocean Delight Squid Rings", price: "28" },
      { name: "Blue Shark Portions", price: "55" },
    ],
  },
];