export interface Recipe {
  slug: string;
  title: string;
  category: string;
  date: string;
  readTime: string;
  image: string;
  excerpt: string;
  intro: string;
  ingredients: string[];
  instructions: string[];
  note?: string;
}

export const RECIPES: Recipe[] = [
  {
    slug: "creamy-chicken-mushroom",
    image: "/images/recipes/creamy-chicken-mushroom.jpg",
    title: "Creamy Chicken & Mushroom",
    category: "Chicken",
    date: "Sep 10, 2020",
    readTime: "1 min read",
    excerpt:
      "Enjoy this delicious, juicy, and tender chicken smothered in mushroom gravy all cooked up in the same pan!",
    intro:
      "Enjoy this delicious, juicy, and tender chicken smothered in mushroom gravy all cooked up in the same pan!",
    ingredients: [
      "8 boneless skinless chicken thighs or breasts",
      "1/2 cup all-purpose flour seasoned (1 tsp salt and 1/4 tsp pepper)",
      "2 tbsp butter",
      "1 tbsp olive oil",
      "8oz sliced mushrooms",
      "3 cloves large garlic, chopped",
      "1 1/2 cups chicken stock or white wine",
      "1/2 cup heavy cream",
      "2 tbsp mustard",
      "1 tbsp thyme",
      "1/2 cup parmesan",
    ],
    instructions: [
      "Add 1 tbsp of butter & olive oil to a skillet on high heat.",
      "Sear chicken on each side until crispy brown.",
      "Remove chicken and reduce heat to medium.",
      "Add 1 tbsp of butter to the skillet along with mushrooms.",
      "Sauté until mushrooms are slightly brown.",
      "Add garlic and thyme until garlic is soft.",
      "Add stock/wine to the pan.",
      "Add cream, mustard, and cheese.",
      "Stir until creamy and combined.",
      "Add salt and pepper to taste.",
    ],
    note: "Items available at Khan's Gulf View Location",
  },
  {
    slug: "spicy-stir-fry-squid-rings",
    image: "/images/recipes/spicy-stir-fry-squid-rings.jpg",
    title: "Spicy Stir-Fry Squid Rings",
    category: "Seafood",
    date: "Sep 10, 2020",
    readTime: "1 min read",
    excerpt:
      "Ocean Delight Squid Rings stir-fried with a spicy twist makes a scrumptious and delightful meal or appetizer.",
    intro:
      "Ocean Delight Squid Rings stir-fried with a spicy twist makes a scrumptious and delightful meal or appetizer. Visit us to pick up your items to make this dish!",
    ingredients: [
      "Ocean Delight Squid Rings",
      "1 tbsp white wine",
      "1/2 tsp sesame oil",
      "5 cups + 1 tbsp vegetable oil",
      "1 tbsp white pepper",
      "1 cup all-purpose flour",
      "1/3 cup breadcrumbs",
      "1 tsp salt",
      "1/2 tsp black pepper",
      "2 hot peppers, chopped",
      "5 cloves garlic, sliced",
      "1 onion, chopped in slices",
      "2 tsp ginger, minced",
      "1 bunch chives, finely chopped",
      "1 bunch fresh parsley, chopped",
    ],
    instructions: [
      "Marinate the squid in the wine and sesame oil.",
      "Heat the oil in a pot until the temperature reaches 325 degrees.",
      "Combine the all-purpose flour, breadcrumbs, salt, and white pepper.",
      "Gently squeeze off any liquid and dredge the squid in the dry mixture.",
      "Fry until golden brown and season with black pepper.",
      "Add a tbsp of vegetable oil to a wok on medium-high heat.",
      "Add the ginger and let it fry in the oil.",
      "Add the garlic, chopped peppers, chives, and onions.",
      "Add the squid to the wok and stir-fry quickly, garnishing with pepper & parsley.",
    ],
    note: "Items available at Khan's Gulf View Location",
  },
  {
    slug: "lobster-tails-garlic-lemon-butter",
    image: "/images/recipes/lobster-tails-garlic-lemon-butter.jpg",
    title: "Lobster Tails with Garlic Lemon Butter",
    category: "Seafood",
    date: "Sep 10, 2020",
    readTime: "1 min read",
    excerpt:
      "Warm garlic lemon butter makes each bite tantalizingly flavourful and tender — easy to make, excellent in flavour and presentation.",
    intro:
      "Lobster meat is a delight in itself and the warm garlic lemon butter makes each bite tantalizingly flavourful and tender. The recipe is easy to make and excellent in flavour and presentation.",
    ingredients: [
      "4 lobster tails",
      "1 tbsp parsley",
      "2 garlic cloves, pressed",
      "1 tsp mustard",
      "1/4 tsp salt",
      "1/8 tsp black pepper",
      "1 1/2 tbsp olive oil",
      "1 1/2 tbsp lemon juice",
      "4 tbsp unsalted butter",
      "2 tbsp butter (for the garlic lemon butter sauce)",
    ],
    instructions: [
      "Preheat oven to broil on high heat.",
      "Butterfly the lobster tails.",
      "In a small bowl, stir together parsley, garlic, mustard, salt, pepper, olive oil and lemon juice.",
      "Place the butterflied lobster tails into a roasting pan.",
      "Divide the marinade evenly over the tops of each tail and dot each tail with 1/2 tbsp of butter.",
      "Broil the lobster tails on high heat 10–11 minutes until white at the center.",
      "Drain drippings from the roasting pan into a small saucepan and combine with 2 tbsp butter.",
      "Bring to a simmer, remove from heat and pour over the lobster tails.",
    ],
    note: "Items available at Khan's Gulf View Location",
  },
  {
    slug: "tilapia-broccoli",
    image: "/images/recipes/tilapia-broccoli.jpg",
    title: "Tilapia & Broccoli",
    category: "Seafood",
    date: "Sep 10, 2020",
    readTime: "1 min read",
    excerpt:
      "Perfectly golden Tilapia with a hint of lemon and herb flavour, paired with seasoned steamed broccoli.",
    intro:
      "Eat healthy with this perfectly golden Tilapia with a hint of lemon and herb flavour paired with seasoned steamed broccoli. Stop in at Khan's Poultry and Meats to pick up a pack of your Tilapia fish fillet and broccoli.",
    ingredients: [
      "4 Tilapia fillets",
      "2 tbsp butter",
      "1 tbsp olive oil",
      "1 tsp garlic, minced",
      "1 tsp chili powder",
      "1 tbsp lemon juice",
      "Salt & pepper to taste",
      "Chopped parsley and sliced lemon for garnish",
      "2 cups broccoli",
      "Parmesan cheese",
    ],
    instructions: [
      "Rinse off the tilapia fillets and pat dry.",
      "Season tilapia with salt, pepper, chili powder & parmesan.",
      "Add butter and oil to a pan over medium heat.",
      "Add garlic and sauté until fragrant.",
      "Cook tilapia fillets in the pan, 3 minutes on each side.",
      "Pour lemon juice over the tilapia and garnish with chopped parsley.",
      "Steam the broccoli and season with salt and pepper.",
    ],
    note: "Items available at Khan's Gulf View Location",
  },
  {
    slug: "orange-glazed-roast-duck",
    image: "/images/recipes/orange-glazed-roast-duck.jpg",
    title: "Orange Glazed Roast Duck",
    category: "Poultry",
    date: "Sep 10, 2020",
    readTime: "1 min read",
    excerpt:
      "This orange glazed marmalade duck is flavourful, moist and slow-roasted to perfection — impressive yet easy.",
    intro:
      "This delicious orange glazed marmalade duck is flavourful, moist and slow-roasted to perfection. It makes an impressive yet easy entrée.",
    ingredients: [
      "Duck — 5 lb whole duck",
      "Duck — 1 tbsp salt",
      "Duck — 1 tbsp five spice powder",
      "Duck — 1 orange, zested and cut into six slices",
      "Duck — 1 tbsp grated ginger",
      "Duck — 1 tbsp grated garlic",
      "Glaze — 1/2 cup orange marmalade",
      "Glaze — 1 tbsp soy sauce",
      "Glaze — 2 tbsp orange juice",
      "Glaze — 1 tsp grated ginger",
    ],
    instructions: [
      "Preheat oven to 350 degrees F.",
      "To prepare the duck, remove any innards and pat the bird dry.",
      "Mix the salt and five-spice powder together and generously season the duck's inside and out.",
      "Combine the garlic, ginger, and orange zest and rub inside the duck.",
      "Stuff the inside with the orange slices and tie the legs together with kitchen twine.",
      "Roast the duck for 1 hour and 15 minutes.",
      "Meanwhile, make the glaze — combine the ingredients, whisking together.",
      "Cook the duck for an additional 35 minutes, glazing three times.",
    ],
    note: "Items available at Khan's Gulf View Location",
  },
  {
    slug: "shrimp-kebabs",
    image: "/images/recipes/shrimp-kebabs.jpg",
    title: "Shrimp Kebabs",
    category: "Seafood",
    date: "Aug 25, 2020",
    readTime: "1 min read",
    excerpt:
      "A healthy & colourful meal marinated in a flavourful blend of honey, garlic & herbs, grilled to perfection.",
    intro:
      "A healthy & colourful meal marinated in a flavourful blend of honey, garlic & herbs grilled to perfection.",
    ingredients: [
      "Marinade — 4 tbsp olive oil",
      "Marinade — 1 tbsp honey",
      "Marinade — 1 1/2 tbsp soy sauce",
      "Marinade — 1 tsp lemon zest",
      "Marinade — 2 tsp parsley leaves, chopped",
      "Marinade — 2 tsp thyme leaves, chopped",
      "Marinade — 1/2 tsp salt",
      "Marinade — 1/4 tsp pepper",
      "Marinade — 1/2 tsp garlic, minced",
      "Kebabs — bamboo skewers",
      "Kebabs — shrimp, peeled and deveined",
      "Kebabs — 1 sweet pepper, chopped",
      "Kebabs — 1 red onion",
      "Kebabs — 1 cup pineapple, chunked",
    ],
    instructions: [
      "Marinate your shrimp & vegetables.",
      "Place the marinated shrimp & vegetables onto the skewers.",
      "Grill kebabs until golden & tender.",
    ],
    note: "Items available at Khan's Gulf View Location",
  },
  {
    slug: "oven-baked-chicken-breast-spinach-mozzarella",
    image: "/images/recipes/oven-baked-chicken-breast-spinach-mozzarella.jpg",
    title: "Oven-Baked Chicken Breast stuffed with Spinach and Mozzarella",
    category: "Chicken",
    date: "Aug 14, 2020",
    readTime: "1 min read",
    excerpt:
      "Delicious and healthy — the perfect lunch or breakfast option.",
    intro: "Delicious and Healthy, Lunch or Breakfast option.",
    ingredients: [
      "4 (6 oz.) boneless, skinless chicken breasts",
      "1/4 tsp salt",
      "1/4 tsp black pepper",
      "1/4 tsp garlic powder",
      "1/2 cup chopped fresh spinach",
      "1/2 cup shredded mozzarella cheese",
      "2 tsp extra virgin olive oil",
      "1 tsp paprika",
      "1/4 cup grated Parmesan cheese",
    ],
    instructions: [
      "Preheat oven to 375. Line a baking sheet with parchment paper and set aside.",
      "Cut each chicken breast and lay open like a book.",
      "Sprinkle the inside of each chicken breast with the salt, pepper and garlic powder.",
      "Top with 2 tbsp chopped spinach and 2 tbsp mozzarella cheese each.",
      "Fold the chicken breasts and lay on the baking sheet.",
      "Drizzle the tops with olive oil, then sprinkle with 1/4 tsp paprika and 1 tbsp Parmesan each.",
      "Bake at 375 for 30–35 minutes, until the chicken breasts are cooked through.",
      "Serve hot and enjoy!",
    ],
    note: "Items available at Khan's Gulf View Location",
  },
  {
    slug: "eggs-benedict-pink-salmon",
    image: "/images/recipes/eggs-benedict-pink-salmon.jpg",
    title: "Eggs Benedict with Pink Salmon",
    category: "Breakfast",
    date: "Aug 14, 2020",
    readTime: "1 min read",
    excerpt: "Start your day right with a healthy balanced breakfast.",
    intro: "Start your day right with a healthy balanced breakfast.",
    ingredients: [
      "4 eggs",
      "2 tbsp white vinegar",
      "2 buns, halved",
      "Butter",
      "8 slices pink salmon",
      "Chives",
      "Hollandaise — 2 tsp lemon juice",
      "Hollandaise — 3 egg yolks",
      "Hollandaise — 125g unsalted butter, diced",
    ],
    instructions: [
      "For the Hollandaise: put the lemon juice and vinegar in a small bowl, add the egg yolks and whisk until light and frothy.",
      "Place the bowl over a pan of simmering water and whisk until the mixture thickens.",
      "Gradually add the butter, whisking constantly until thick.",
      "Remove from heat and whisk for a few minutes, then season and keep warm.",
      "To poach the eggs: bring water to a boil and add the vinegar.",
      "Lower the heat so the water is simmering gently.",
      "Stir the water so you have a slight whirlpool, then slide in the eggs one by one.",
      "Cook each for about 4 mins, then remove with a spoon.",
      "Lightly toast and butter the bread, and place slices of salmon on each half.",
      "Top each with an egg, spoon over some Hollandaise and garnish with chopped chives.",
    ],
    note: "Items available at Khan's Gulf View Location",
  },
  {
    slug: "steak-marinade",
    image: "/images/recipes/steak-marinade.jpg",
    title: "Steak Marinade",
    category: "Beef",
    date: "Aug 14, 2020",
    readTime: "1 min read",
    excerpt:
      "Dinner made easy — create this mouth-watering marinade steak with succulent beef steaks.",
    intro:
      "Dinner made easy... Create this mouth-watering marinade steak. Stop by any of our Khan's locations to pick up your succulent beef steaks.",
    ingredients: [
      "1/3 cup soy sauce",
      "1/4 cup lemon juice",
      "1/2 cup olive oil",
      "1/4 cup Worcestershire sauce",
      "2 tsp minced garlic",
      "1 tbsp Italian seasoning",
      "1 tsp black pepper",
      "1/2 tsp salt",
      "1/2 tsp onion powder",
      "Steak",
    ],
    instructions: [
      "Place all the ingredients in a bowl.",
      "Mix to combine.",
      "Add the steaks to the marinade.",
      "Marinate for at least 1 hour.",
      "Cook the steak as desired.",
    ],
    note: "Marinade makes enough for 2lbs of Steak",
  },
];

export function getRecipe(slug: string) {
  return RECIPES.find((r) => r.slug === slug);
}